{% set python_min = "3.11" %}
{% set name = "nionui" %}
{% set version = "10.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  #Use pypi for the next release, source distribution missing files
  #url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  #sha256: 85c4a64e6a30be2b601f05680e809712589c6dbb561426d4d5e0f35ef5f97e54
  url: https://github.com/nion-software/nionui/archive/{{ version }}.tar.gz
  sha256: b7bee01b94f6373d61fd4e0c7f4ab912abc31aa5d4aebebf752f12731d0b7ed9

build:
  number: 0
  noarch: python
  entry_points:
    - nionui=nion.ui.command:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - imageio
    - nionutils >=4.14,<5.0
    - numpy >=2.0,<3.0
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - nion.ui
    - nion.ui.test

about:
  home: https://github.com/nion-software/nionui
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Nion UI framework.
  dev_url: https://github.com/nion-software/nionui

extra:
  recipe-maintainers:
    - cmeyer
    - nion-gwyn
